# Registration route
POST http://localhost:5000/register HTTP/1.1
Content-Type: application/json

{
    "first_name": "Théo",
    "last_name": "Sueur Verdier",
    "email": "theo.sueur@gmail.com",
    "passwd": "1234"
}

###

# Login route
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json
  
{
    "email": "theo.sueur@gmail.com",
    "passwd": "1234"
}

###

# Root route
GET http://localhost:5000 HTTP/1.1
x-access-tokens: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjY5OTc1NzkwLjB9.v6bpQL2ACn-iY0shknnG3v15ZlqPTnqRIA-cJv8AexA

###

# Get token route
POST http://localhost:5000/get-token HTTP/1.1
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjY5OTc1NzkwLjB9.Jv3cKfR3gCAuoXJ7YqkBpFsGQVlgOvwuW7AQHK9bQOU"
}

###

# Logout route
POST http://localhost:5000/logout HTTP/1.1
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjY5OTc1NzkwLjB9.Jv3cKfR3gCAuoXJ7YqkBpFsGQVlgOvwuW7AQHK9bQOU"
}

###

# Add todo route
POST http://localhost:5000/add-todo HTTP/1.1
x-access-tokens: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjY5OTc1NzkwLjB9.v6bpQL2ACn-iY0shknnG3v15ZlqPTnqRIA-cJv8AexA
Content-Type: application/json

{
    "name": "Finir ce projet très cool",
    "important": 0
}

###

# Update todo route
PATCH http://localhost:5000/update-todo HTTP/1.1
x-access-tokens: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjY5OTc1NzkwLjB9.v6bpQL2ACn-iY0shknnG3v15ZlqPTnqRIA-cJv8AexA
Content-Type: application/json

{
    "id": 1,
    "name": "Finir ce super projet",
    "important": 1
}

###

# Get todos route
GET http://localhost:5000/get-todos HTTP/1.1
x-access-tokens: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjY5OTc1NzkwLjB9.v6bpQL2ACn-iY0shknnG3v15ZlqPTnqRIA-cJv8AexA
Content-Type: application/json

{

    "name": "Finir ce super projet",
    "important": 0
}
