# Registration route
POST http://localhost:5000/register HTTP/1.1
Content-Type: application/json

{
    "first_name": "Théo",
    "last_name": "Sueur Verdier",
    "email": "theo.sueur@gmail.com",
    "passwd": "1234"
}

###

# Login route
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json
  
{
    "email": "theo.sueur@gmail.com",
    "passwd": "1234"
}

###

# Root route
GET http://localhost:5000 HTTP/1.1
x-access-tokens: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjY5OTIzMTM3LjB9.0-ALXn-hthImHSDdJUJPwjbk8aO0Tkdoz2HlDe-FTbI

###

# Get token route
POST http://localhost:5000/get-token HTTP/1.1
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjcwMDEwMTMyLjB9.op6Z0WlVykHykCj3pArxthjRkFnrCKcOGUSNLnu-LUU"
}

###

# Logout route
POST http://localhost:5000/logout HTTP/1.1
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Njk0NjMzMjUuMH0.AMg9jbbQ70K7T_0BhConJnmAgzyeUbyvAEQycRbVJR8"
}

###

# Add todo route
POST http://localhost:5000/add-todo HTTP/1.1
x-access-tokens: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjY5OTI0MzMyLjB9.TU8INOAfxlV0groyPaR7Cg0xslERvgIOV_jH98zB8q8
Content-Type: application/json

{
    "name": "Finir ce projet génial",
    "important": 0
}

###

# Get todo route
GET http://localhost:5000/get-todos HTTP/1.1
x-access-tokens: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjY5OTI0MzMyLjB9.TU8INOAfxlV0groyPaR7Cg0xslERvgIOV_jH98zB8q8
Content-Type: application/json

{
    "name": "Finir ce super projet",
    "important": 0
}
