# Registration route
POST http://localhost:5000/register HTTP/1.1
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "john.doe@gmail.com",
    "passwd": "1234"
}

###

POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json
  
{
    "email": "john.doe@gmail.com",
    "passwd": "1234"
}

###

GET http://localhost:5000 HTTP/1.1
x-access-tokens: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Njk0MDU0NDkuMH0.GYU1QJ-IprHKInkusqmk48O5mcJCt4_ZTVX85aoxkM8

###

POST http://localhost:5000/get-token HTTP/1.1
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Njk0MDYzMTkuMH0.VIQBn3Ut9v5HwM0_1gh9fRT-1WTua7ueSfsdS2wtk-4"
}
